Repository Team-Ezel/VOZA-client-v1, pull requests merged in 2023-11, with the labels that each got.

#32 🔀: 헤더 프로필사진 적용
  src/components/Common/atoms/MenuItems/Profile/index.tsx
  src/components/Common/atoms/MenuItems/Profile/style.ts
  src/types/components/common/ProfileURLPropsType.ts
Labels: Priority: Medium, 📬 Type: API, 🎨 Type: Publishing

#33 로그인 확인 훅 만듦
  src/components/Promotion/atoms/LoginBtn/index.tsx
  src/components/Search/templates/index.tsx
  src/components/Search/templates/style.ts
  src/hooks/useLoginCheck.ts
  src/pages/search/index.tsx
Labels: 🪧Type: feat

#34 🔀: 캘린더페이지 기능 구현
  src/components/Calender/molecules/DateInputList/index.tsx
  src/components/Calender/molecules/ScheduleList/index.tsx
  src/components/Calender/organisms/CalenderModal/index.tsx
  src/components/Calender/organisms/Schedule/index.tsx
  src/components/Main/atoms/Item/MyClassItem/index.tsx
  src/components/Main/atoms/Item/MyClassItem/style.ts
  src/components/Main/molecules/MainPageBarList/style.ts
  src/components/Main/molecules/MyClassList/index.tsx
  src/components/Main/molecules/MyClassList/style.ts
  src/components/Main/organisms/MainPageBar/index.tsx
  src/components/Main/organisms/MyClass/index.tsx
  src/components/Main/organisms/MyClass/style.ts
  src/pages/group/[id]/calender/index.tsx
  src/types/components/Calender/ScheduleTypes.ts
  src/types/components/Main/MyClassType.ts
Labels: 📬 Type: API

#35 그룹 메인페이지 기능 구현
  src/assets/svgs/Right_arrow.tsx
  src/atoms/atoms.ts
  src/components/Board/atoms/item/BoardPostItem/index.tsx
  src/components/Board/atoms/item/BoardPostItem/style.ts
  src/components/Board/atoms/modal/WriteModal/index.tsx
  src/components/Board/atoms/modal/WriteModal/style.ts
  src/components/Board/molecules/BoardInfo/index.tsx
  src/components/Board/molecules/BoardInfo/style.ts
  src/components/Board/molecules/PostList/index.tsx
  src/components/Board/molecules/PostList/style.ts
  src/components/Board/templates/boardTemplates/index.tsx
  src/components/Board/templates/boardTemplates/style.ts
  src/components/Main/atoms/Modal/Category/index.tsx
  src/components/Search/molecules/SearchPostlists/index.tsx
  src/components/Search/templates/SearchTemplates/index.tsx
  src/pages/group/[id]/index.tsx
  src/types/components/board/BoardPostType.ts
Labels: 🪧Type: feat, 📬 Type: API, 🎨 Type: Publishing

#37 🔀: 메인 페이지 기능구현
  src/apis/.gitkeep
  src/components/Main/atoms/Item/NewClass/index.tsx
  src/components/Main/atoms/Item/OtherClassItem/index.tsx
  src/components/Main/atoms/Item/OtherClassItem/style.ts
  src/components/Main/atoms/Item/RecommendClassItem/index.tsx
  src/components/Main/atoms/Modal/Category/index.tsx
  src/components/Main/atoms/Modal/ClassName/index.tsx
  src/components/Main/atoms/Modal/Profile/index.tsx
  src/components/Main/atoms/Modal/Profile/style.ts
  src/components/Main/molecules/NewClassModalSelect/index.tsx
  src/components/Main/molecules/OtherClassList/index.tsx
  src/components/Main/molecules/RecommendClassList/index.tsx
  src/components/Main/organisms/MyClass/index.tsx
  src/components/Main/organisms/NewClassModal/index.tsx
  src/components/Main/organisms/NewClassModal/style.ts
  src/components/Main/organisms/OtherClass/index.tsx
  src/components/Main/organisms/RecommendClass/index.tsx
  src/hooks/.gitkeep
  src/hooks/useFetchFormdata.tsx
  src/pages/main/index.tsx
  src/types/components/Main/OtherClassTypes.ts
  src/types/components/Main/RecommendClassType.ts
  src/types/components/common/NewClassModal.ts
Labels: Priority: Medium, 🪧Type: feat, 📬 Type: API

#38 🔀:초대코드로 그룹가입기능 추가
  src/components/Common/atoms/MenuItems/Profile/index.tsx
  src/components/Common/molecules/JoinCodeModal/index.tsx
  src/components/Common/molecules/JoinCodeModal/style.ts
  src/components/Common/molecules/MenuModal/index.tsx
  src/components/Common/molecules/MenuModal/style.ts
  src/components/Common/organisms/Header/index.tsx
Labels: Priority: Medium, 🪧Type: feat, 📬 Type: API, 🎨 Type: Publishing

#40 게시글 상세 페이지 프로모션 및 기능구현
  src/atoms/atoms.ts
  src/components/Board/atoms/item/BoardPostItem/index.tsx
  src/components/Calender/atoms/CalenderItem/index.tsx
  src/components/Calender/atoms/CalenderWeek/index.tsx
  src/components/Calender/atoms/DateInput/index.tsx
  src/components/Calender/atoms/ScheduleItem/index.tsx
  src/components/Calender/atoms/ScheduleOptionItem/index.tsx
  src/components/Calender/molecules/CalenderChange/index.tsx
  src/components/Calender/molecules/CalenderList/index.tsx
  src/components/Calender/molecules/DateInputList/index.tsx
  src/components/Calender/molecules/ScheduleList/index.tsx
  src/components/Calender/organisms/CalenderBox/index.tsx
  src/components/Calender/organisms/Schedule/index.tsx
  src/components/Post/molecules/PostInfo/index.tsx
  src/components/Post/molecules/PostInfo/style.ts
  src/components/Post/organisms/PostOrganisms/index.tsx
  src/components/Post/organisms/PostOrganisms/style.ts
  src/components/Post/templates/PostTemplates/index.tsx
  src/components/Post/templates/PostTemplates/style.ts
  src/components/Write/organisms/WriteBox/index.tsx
  src/pages/group/[id]/post/[postId]/index.tsx
  src/types/components/post/EditPostType.ts
  src/types/components/post/PostType.ts
Labels: 🪧Type: feat, 📬 Type: API, 🎨 Type: Publishing

#42 🔀 : 추천 그룹 api 수정 및 style 변경
  src/components/Main/atoms/Item/RecommendClassItem/index.tsx
  src/components/Main/atoms/Item/RecommendClassItem/style.ts
  src/components/Main/organisms/RecommendClass/index.tsx
Labels: 📬 Type: API
