Repository Team-Ezel/VOZA-client-v1, pull requests merged in 2023-09, with the labels that each got.

#2 🔀 : MyClass컴포넌트 퍼블리싱
  src/assets/pngs/Bowling.png
  src/assets/svgs/Add_ circle.tsx
  src/assets/svgs/Default_image.tsx
  src/assets/svgs/index.ts
  src/components/Main/atoms/MyClassItem/index.tsx
  src/components/Main/atoms/MyClassItem/style.ts
  src/components/Main/atoms/NewClass/index.tsx
  src/components/Main/atoms/NewClass/style.ts
  src/components/Main/atoms/RecommendClassItem/index.tsx
  src/components/Main/atoms/RecommendClassItem/style.ts
  src/components/Main/molecules/MyClassList/index.tsx
  src/components/Main/molecules/MyClassList/style.ts
  src/components/Main/molecules/RecommendClassList/index.tsx
  src/components/Main/molecules/RecommendClassList/style.ts
  src/components/Main/organisms/MyClass/index.tsx
  src/components/Main/organisms/MyClass/style.ts
  src/components/Main/organisms/RecommendClass/index.tsx
  src/components/Main/organisms/RecommendClass/style.ts
  src/pages/_app.tsx
  src/pages/main.tsx
  src/styles/globals.tsx
  src/types/components/common/MyClassType.ts
  src/types/components/common/RecommendClassType.ts
Labels: Priority: Medium, 🎨 Type: Publishing

#3 🔀 : Header 컴포넌트 퍼블리싱
  src/assets/svgs/Add_outline.tsx
  src/assets/svgs/Arrow_down.tsx
  src/assets/svgs/Arrow_up.tsx
  src/assets/svgs/Chat.tsx
  src/assets/svgs/Chat_filled.tsx
  src/assets/svgs/Default_profile.tsx
  src/assets/svgs/Logo.tsx
  src/assets/svgs/Search.tsx
  src/assets/svgs/index.ts
  src/components/Common/atoms/MenuItems/Chatting/index.tsx
  src/components/Common/atoms/MenuItems/Profile/index.tsx
  src/components/Common/atoms/MenuItems/Profile/style.ts
  src/components/Common/atoms/MenuItems/SearchBar/index.tsx
  src/components/Common/atoms/MenuItems/SearchBar/style.ts
  src/components/Common/molecules/.gitkeep
  src/components/Common/molecules/ChatModal/index.tsx
  src/components/Common/molecules/ChatModal/style.ts
  src/components/Common/molecules/MenuModal/index.tsx
  src/components/Common/molecules/MenuModal/style.ts
  src/components/Common/organisms/.gitkeep
  src/components/Common/organisms/Header/index.tsx
  src/components/Common/organisms/Header/style.ts
Labels: Priority: Medium, 🎨 Type: Publishing

#5 🔀: main page 퍼블리싱
  src/assets/data/MainPageBarListData.ts
  src/assets/data/OtherClassFilterListData.ts
  src/assets/pngs/index.ts
  src/assets/svgs/Arrow_down_fill.tsx
  src/assets/svgs/index.ts
  src/components/Main/atoms/MainPageBarItem/index.tsx
  src/components/Main/atoms/MainPageBarItem/style.ts
  src/components/Main/atoms/MyClassItem/index.tsx
  src/components/Main/atoms/OtherClassFilterItem/index.tsx
  src/components/Main/atoms/OtherClassFilterItem/style.ts
  src/components/Main/atoms/OtherClassItem/index.tsx
  src/components/Main/atoms/OtherClassItem/style.ts
  src/components/Main/atoms/RecommendClassItem/index.tsx
  src/components/Main/atoms/RecommendClassItem/style.ts
  src/components/Main/molecules/MainPageBarList/index.tsx
  src/components/Main/molecules/MainPageBarList/style.ts
  src/components/Main/molecules/MyClassList/index.tsx
  src/components/Main/molecules/MyClassList/style.ts
  src/components/Main/molecules/OtherClassFilter/index.tsx
  src/components/Main/molecules/OtherClassFilter/style.ts
  src/components/Main/molecules/OtherClassList/index.tsx
  src/components/Main/molecules/OtherClassList/style.ts
  src/components/Main/molecules/RecommendClassList/index.tsx
  src/components/Main/molecules/RecommendClassList/style.ts
  src/components/Main/organisms/MainPageBar/index.tsx
  src/components/Main/organisms/MainPageBar/style.ts
  src/components/Main/organisms/OtherClass/index.tsx
  src/components/Main/organisms/OtherClass/style.ts
  src/components/Main/organisms/RecommendClass/index.tsx
  src/components/Main/organisms/RecommendClass/style.ts
  src/pages/main.tsx
  src/pages/main/index.tsx
  src/pages/main/layout.tsx
  src/pages/main/otherClass/index.tsx
  src/styles/globals.tsx
  src/types/components/Main/MainPageBarTypes.ts
  src/types/components/Main/MyClassType.ts
  src/types/components/Main/OtherClassTypes.ts
  src/types/components/Main/RecommendClassType.ts
  src/types/components/common/MyClassType.ts
  tsconfig.json
Labels: Priority: High, 🎨 Type: Publishing

#7 🔀: Add OtherFilteritem animations
  src/atoms/.gitkeep
  src/atoms/atoms.ts
  src/components/Common/organisms/Header/style.ts
  src/components/Main/atoms/Item/MainPageBarItem/index.tsx
  src/components/Main/atoms/Item/MainPageBarItem/style.ts
  src/components/Main/atoms/Item/MyClassItem/index.tsx
  src/components/Main/atoms/Item/MyClassItem/style.ts
  src/components/Main/atoms/Item/NewClass/index.tsx
  src/components/Main/atoms/Item/NewClass/style.ts
  src/components/Main/atoms/Item/OtherClassFilterItem/index.tsx
  src/components/Main/atoms/Item/OtherClassFilterItem/style.ts
  src/components/Main/atoms/Item/OtherClassItem/index.tsx
  src/components/Main/atoms/Item/OtherClassItem/style.ts
  src/components/Main/atoms/Item/RecommendClassItem/index.tsx
  src/components/Main/atoms/Item/RecommendClassItem/style.ts
  src/components/Main/atoms/OtherClassFilterItem/index.tsx
  src/components/Main/atoms/OtherClassFilterItem/style.ts
  src/components/Main/molecules/MainPageBarList/index.tsx
  src/components/Main/molecules/MyClassList/index.tsx
  src/components/Main/molecules/OtherClassFilter/index.tsx
  src/components/Main/molecules/OtherClassList/index.tsx
  src/components/Main/molecules/RecommendClassList/index.tsx
  src/components/Main/organisms/NewClassModal/index.tsx
  src/components/Main/organisms/NewClassModal/style.ts
  src/pages/_app.tsx
  src/pages/main/index.tsx
Labels: Priority: Medium, 🪧Type: feat

#8 🔀: Update style
  src/components/Common/molecules/ChatModal/style.ts
  src/components/Common/molecules/MenuModal/index.tsx
  src/components/Common/molecules/MenuModal/style.ts
Labels: Priority: Medium, 🎨 Type: Publishing

#9 🔀: 다른모임 추천 페이지 스타일 수정
  src/components/Main/atoms/Item/OtherClassFilterItem/style.ts
  src/components/Main/atoms/Item/OtherClassItem/style.ts
  src/components/Main/molecules/OtherClassFilter/style.ts
  src/components/Main/molecules/OtherClassList/style.ts
  src/pages/main/otherClass/index.tsx
Labels: Priority: Medium, 🎨 Type: Publishing

#10 🔀: 메인페이지 소모임 생성 모달 추가
  src/assets/data/NewClassModalCategoryListData.ts
  src/assets/svgs/Camera.tsx
  src/assets/svgs/index.ts
  src/atoms/atoms.ts
  src/components/Common/atoms/Button/Button/index.tsx
  src/components/Common/atoms/Button/Button/style.ts
  src/components/Main/atoms/Item/NewClass/index.tsx
  src/components/Main/atoms/Modal/Category/index.tsx
  src/components/Main/atoms/Modal/Category/style.ts
  src/components/Main/atoms/Modal/ClassName/index.tsx
  src/components/Main/atoms/Modal/ClassName/style.ts
  src/components/Main/atoms/Modal/Profile/index.tsx
  src/components/Main/atoms/Modal/Profile/style.ts
  src/components/Main/molecules/NewClassModalSelect/index.tsx
  src/components/Main/molecules/NewClassModalSelect/style.ts
  src/components/Main/organisms/NewClassModal/index.tsx
  src/components/Main/organisms/NewClassModal/style.ts
  src/pages/main/index.tsx
  src/types/components/common/ButtonProps.ts
  src/types/components/common/NewClassModal.ts
  src/types/components/common/NewClassModalButton.ts
  src/utils/isNotNull.ts
Labels: Priority: Medium, 🎨 Type: Publishing

#12 🔀: 메인페이지 반응형, 적응형 작업
  src/components/Main/atoms/Item/MyClassItem/style.ts
  src/components/Main/atoms/Item/NewClass/style.ts
  src/components/Main/atoms/Item/RecommendClassItem/style.ts
  src/components/Main/molecules/MyClassList/style.ts
  src/components/Main/molecules/RecommendClassList/style.ts
  src/components/Main/organisms/MyClass/style.ts
  src/components/Main/organisms/RecommendClass/index.tsx
  src/components/Main/organisms/RecommendClass/style.ts
Labels: Priority: Medium, 🎨 Type: Publishing
