Repository Team-Ezel/VOZA-client-v1, pull requests merged in 2023-12, with the labels that each got.

#44 🔀 : VOZA 로고 클릭시 /main으로 이동
  src/components/Common/organisms/Header/index.tsx
Labels: ⚡Type: Simple, Priority: Low

#45 🔀 : 멤버페이지 스크롤 수정
  src/components/Member/molecules/MemberList/style.ts
Labels: ⚡Type: Simple, Priority: Low, 🎨 Type: Publishing

#46 경로관련 버그 수정
  src/assets/data/BoardHeaderListData.ts
  src/components/Board/molecules/BoardHeaderItem/index.tsx
  src/components/Board/molecules/BoardInfo/style.ts
  src/components/Calender/atoms/CalenderItem/index.tsx
  src/components/Calender/atoms/CalenderWeek/index.tsx
  src/components/Calender/atoms/DateInput/index.tsx
  src/components/Calender/atoms/ScheduleItem/index.tsx
  src/components/Calender/atoms/ScheduleOptionItem/index.tsx
  src/components/Calender/molecules/CalenderChange/index.tsx
  src/components/Calender/molecules/CalenderList/index.tsx
  src/components/Calender/molecules/DateInputList/index.tsx
  src/components/Calender/molecules/ScheduleList/index.tsx
  src/components/Calender/organisms/CalenderBox/index.tsx
  src/components/Calender/organisms/Schedule/index.tsx
  src/components/Common/organisms/GroupCategories/index.tsx
  src/components/CreateVote/atoms/ExtraOptionInput/index.tsx
  src/components/CreateVote/molecules/VoteForm/index.tsx
  src/components/Member/atoms/Modal/GroupCodeModal/index.tsx
  src/components/Post/organisms/PostOrganisms/index.tsx
  src/components/Search/atoms/FilterBtn/index.tsx
  src/components/Search/atoms/FilterBtn/style.ts
  src/components/Search/atoms/SearchTab/index.tsx
  src/components/Search/atoms/SearchTab/style.ts
  src/components/Search/molecules/SearchMolecules/index.tsx
  src/components/Search/molecules/SearchMolecules/style.ts
  src/components/Search/molecules/SearchPostlists/index.tsx
  src/components/Search/molecules/SearchPostlists/style.ts
  src/components/Search/organisms/SearchOrganisms/index.tsx
  src/components/Search/organisms/SearchOrganisms/style.ts
  src/components/Search/templates/SearchTemplates/index.tsx
  src/components/Search/templates/SearchTemplates/style.ts
  src/components/Search/templates/index.tsx
  src/components/Search/templates/style.ts
  src/components/Write/molecules/Toolbar/index.tsx
  src/components/Write/organisms/WriteBox/index.tsx
  src/pages/search/index.tsx
Labels: 🐞 Type: Bug

#52 group페이지 스타일, 게시글 링크 문제 해결
  src/apis/TokenManager.ts
  src/apis/index.ts
  src/components/Board/atoms/item/BoardPostItem/index.tsx
  src/components/Board/molecules/PostList/style.ts
  src/components/Common/molecules/MenuModal/index.tsx
  src/components/Post/molecules/PostInfo/index.tsx
  src/components/Write/atoms/ContentInput/index.tsx
  src/types/components/board/BoardPostType.ts
Labels: ⚡Type: Simple, 🎨 Type: Publishing

#50 🔀 : 투표페이지 제작 및 수정
  src/assets/svgs/Checked.tsx
  src/assets/svgs/index.ts
  src/components/CreateVote/atoms/ExtraOptionInput/index.tsx
  src/components/CreateVote/molecules/VoteForm/index.tsx
  src/components/Vote/atoms/VoteBar/index.tsx
  src/components/Vote/atoms/VoteBar/style.ts
  src/components/Vote/molecules/VoteInfo/index.tsx
  src/components/Vote/molecules/VoteInfo/style.ts
  src/components/Vote/organisms/VoteOrganisms/index.tsx
  src/components/Vote/organisms/VoteOrganisms/style.ts
  src/components/Vote/templates/VoteTemplates/index.tsx
  src/components/Vote/templates/VoteTemplates/style.ts
  src/pages/group/[id]/vote/[voteId]/index.tsx
  src/types/components/Vote/VoteType.ts
  yarn.lock
Labels: 🪧Type: feat, Priority: High, 🐞 Type: Bug, 🎨 Type: Publishing

#51 🔀 : 멤버페이지 리더 검사
  src/components/Member/atoms/Items/MemberListItem/index.tsx
  src/components/Member/molecules/MemberList/index.tsx
Labels: ⚡Type: Simple, Priority: High

#49 :lipstick: :Member MenuBar 수정
  src/components/Common/molecules/MenuModal/index.tsx
  src/components/Common/molecules/MenuModal/style.ts
Labels: Priority: Medium, 🎨 Type: Publishing
