Repository Team-Ezel/VOZA-client-v1, pull requests merged in 2023-10, with the labels that each got.

#13 Feat/header
  src/components/Common/organisms/Header/style.ts
  src/pages/main/index.tsx
  src/pages/main/otherClass/index.tsx
Labels: ⚡Type: Simple

#15 🔀 글작성 퍼블리싱
  src/assets/svgs/Arrow_down_2.tsx
  src/assets/svgs/index.ts
  src/components/Write/atoms/Category/index.tsx
  src/components/Write/atoms/Category/style.ts
  src/components/Write/atoms/ContentInput/index.tsx
  src/components/Write/atoms/ContentInput/style.ts
  src/components/Write/atoms/NameInput/index.tsx
  src/components/Write/atoms/NameInput/style.ts
  src/components/Write/molecules/Contents/index.tsx
  src/components/Write/molecules/Contents/style.ts
  src/components/Write/organisms/WriteBox/index.tsx
  src/components/Write/organisms/WriteBox/style.ts
  src/pages/test/index.tsx
Labels: Priority: Medium, 🎨 Type: Publishing

#17 🔀: 글로벌 스타일 폰트 재적용
  src/components/Write/atoms/Category/index.tsx
  src/components/Write/atoms/ContentInput/index.tsx
  src/components/Write/atoms/NameInput/index.tsx
  src/components/Write/molecules/Contents/index.tsx
  src/components/Write/organisms/WriteBox/index.tsx
  src/pages/test/index.tsx
  src/styles/globals.tsx
  src/types/components/Write/ContentsType.ts
Labels: ⚡Type: Simple, Priority: Low

#23 그룹 페이지 퍼블리싱
  src/apis/index.ts
  src/assets/data/BoardHeaderListData.ts
  src/assets/data/MainPageBarListData.ts
  src/assets/data/OtherClassFilterListData.ts
  src/assets/svgs/NoPostSvg.tsx
  src/assets/svgs/NoVoteSvg.tsx
  src/components/Board/atoms/BoardPostItem/index.tsx
  src/components/Board/atoms/BoardPostItem/style.ts
  src/components/Board/molecules/BoardHeaderItem/index.tsx
  src/components/Board/molecules/BoardHeaderItem/style.ts
  src/components/Board/molecules/BoardInfo/index.tsx
  src/components/Board/molecules/BoardInfo/style.ts
  src/components/Board/molecules/PostList/index.tsx
  src/components/Board/molecules/PostList/style.ts
  src/components/Board/organisms/BoardHeader/index.tsx
  src/components/Board/organisms/BoardHeader/style.ts
  src/components/Board/templates/boardTemplates/index.tsx
  src/components/Board/templates/boardTemplates/style.ts
  src/pages/board/index.tsx
  src/types/components/board/BoardInfoType.ts
  src/types/components/board/BoardPostType.ts
  src/types/components/board/BoardVoteType.ts
Labels: 🎨 Type: Publishing

#25 Search 페이지 퍼블리싱
  src/assets/svgs/Filter.tsx
  src/components/Board/organisms/BoardHeader/index.tsx
  src/components/Search/atoms/FilterBtn/index.tsx
  src/components/Search/atoms/FilterBtn/style.ts
  src/components/Search/atoms/SearchTab/index.tsx
  src/components/Search/atoms/SearchTab/style.ts
  src/components/Search/molecules/SearchMolecules/index.tsx
  src/components/Search/molecules/SearchMolecules/style.ts
  src/components/Search/molecules/SearchPostlists/index.tsx
  src/components/Search/molecules/SearchPostlists/style.ts
  src/components/Search/organisms/SearchOrganisms/index.tsx
  src/components/Search/organisms/SearchOrganisms/style.ts
  src/components/Search/templates/SearchTemplates/index.tsx
  src/components/Search/templates/SearchTemplates/style.ts
  src/pages/search/index.tsx
  src/types/components/board/BoardPostType.ts
Labels: 🎨 Type: Publishing

#27 🔀: 캘린더 페이지 퍼블리싱 및 로직 추가작성
  package-lock.json
  package.json
  src/assets/data/CalenderWeekListData.ts
  src/assets/data/ScheduleListDummy.ts
  src/assets/svgs/Add.tsx
  src/assets/svgs/Arrow_left.tsx
  src/assets/svgs/Arrow_right.tsx
  src/assets/svgs/Calender.tsx
  src/assets/svgs/Calender_2.tsx
  src/assets/svgs/Camera.tsx
  src/assets/svgs/Default_image.tsx
  src/assets/svgs/Logo.tsx
  src/assets/svgs/Timer.tsx
  src/assets/svgs/Wave.tsx
  src/assets/svgs/index.ts
  src/atoms/atoms.ts
  src/components/Calender/atoms/AddScheduleItem/index.tsx
  src/components/Calender/atoms/AddScheduleItem/style.ts
  src/components/Calender/atoms/CalenderItem/index.tsx
  src/components/Calender/atoms/CalenderItem/style.ts
  src/components/Calender/atoms/CalenderWeek/index.tsx
  src/components/Calender/atoms/CalenderWeek/style.ts
  src/components/Calender/atoms/DateInput/index.tsx
  src/components/Calender/atoms/DateInput/style.ts
  src/components/Calender/atoms/ScheduleItem/index.tsx
  src/components/Calender/atoms/ScheduleItem/style.ts
  src/components/Calender/atoms/ScheduleOptionItem/index.tsx
  src/components/Calender/atoms/ScheduleOptionItem/style.ts
  src/components/Calender/molecules/CalenderChange/index.tsx
  src/components/Calender/molecules/CalenderChange/style.ts
  src/components/Calender/molecules/CalenderList/index.tsx
  src/components/Calender/molecules/CalenderList/style.ts
  src/components/Calender/molecules/DateInputList/index.tsx
  src/components/Calender/molecules/DateInputList/style.ts
  src/components/Calender/molecules/ScheduleList/index.tsx
  src/components/Calender/molecules/ScheduleList/style.ts
  src/components/Calender/organisms/CalenderBox/index.tsx
  src/components/Calender/organisms/CalenderBox/style.ts
  src/components/Calender/organisms/CalenderModal/index.tsx
  src/components/Calender/organisms/CalenderModal/style.ts
  src/components/Calender/organisms/Schedule/index.tsx
  src/components/Calender/organisms/Schedule/style.ts
  src/components/Calender/templates/CalenderTemplates/style.ts
  src/components/Common/atoms/TitleBox/index.tsx
  src/components/Common/atoms/TitleBox/style.ts
  src/pages/group/[groupId]/calender/index.tsx
  src/pages/test/index.tsx
  src/styles/globals.tsx
  src/types/components/Calender/CalenderType.ts
  src/types/components/Calender/ScheduleTypes.ts
  src/types/components/common/TitleBoxType.ts
  src/utils/buildCalender.ts
  yarn.lock
Labels: Priority: Medium, 🎨 Type: Publishing

#28 🔀:투표 생성 페이지 로직 작성
  src/assets/svgs/Cross.tsx
  src/components/CreateVote/atoms/Input/index.tsx
  src/components/CreateVote/molecules/VoteForm/index.tsx
  src/pages/group/[id]/createvote/index.tsx
Labels: Priority: Medium, 🪧Type: feat

#29 🔀: api통신관련 hook 추가
  src/hooks/useFetch.tsx
  src/hooks/useFetchFormdata.tsx
Labels: Priority: Medium, 📬 Type: API

#30 Fix/hotfix
  package.json
  src/assets/svgs/index.ts
  src/pages/group/[id]/calender/index.tsx
Labels: ⚡Type: Simple
